import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import { GoogleAnalytics } from "@next/third-parties/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "y9lK8HBOIa0Bxa9WPEIcdrBybwWf2eGJ5VoSKb5nvR8",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png"></link>
        <meta
          name="google-site-verification"
          content="y9lK8HBOIa0Bxa9WPEIcdrBybwWf2eGJ5VoSKb5nvR8"
        />
      </head>
      <body className={inter.className}>
        <main>{children}</main>
        <GoogleAnalytics gtmId="G-LNFJ323V57" />
      </body>
    </html>
  );
}
